import type { ModelSpec } from "./types";

// Model catalog grouped by production lane, following the primer:
//   Soul → people · Seedream/Flux → products · Ideogram/Recraft → words & layout
//   Qwen → repair shop · Z-Image/Pixverse/fast Wan → cheap exploration
//   Seedance → longer cinematic scenes · Kling → hero shot · Wan/Minimax → speech
//   Kling Motion Control → copy a performance · Topaz & finishing → delivery
//
// Prices are illustrative list prices for estimates. In live mode the server
// replaces them with Higgsfield's published pricing when it can fetch it.
export const MODEL_CATALOG: ModelSpec[] = [
  {
    id: "higgsfield-soul",
    name: "Soul",
    family: "soul",
    vendor: "Higgsfield",
    origin: "US",
    kind: "image",
    lanes: ["people"],
    price: 0.04,
    unit: "image",
    strengths: "Fashion & editorial people, identity, culturally current portraits, founder shoots.",
    watchOuts: "Packaging, logos and small legal copy — handle those in a separate step.",
    quality: 5,
  },
  {
    id: "seedream-4",
    name: "Seedream 4",
    family: "seedream",
    vendor: "ByteDance",
    origin: "CN",
    kind: "image",
    lanes: ["product"],
    price: 0.03,
    unit: "image",
    strengths: "Places one clean product reference into lifestyle or campaign worlds while staying recognizable.",
    watchOuts: "Check labels, exact colors and small geometry against the original product.",
    quality: 5,
  },
  {
    id: "flux-kontext-pro",
    name: "Flux Kontext Pro",
    family: "flux",
    vendor: "Black Forest Labs",
    origin: "DE",
    kind: "image",
    lanes: ["product"],
    price: 0.04,
    unit: "image",
    strengths: "Reference-faithful product scenes and consistent subjects across a set.",
    watchOuts: "Labels, exact brand colors and fine geometry still need a QA pass.",
    quality: 4,
  },
  {
    id: "ideogram-v3",
    name: "Ideogram 3",
    family: "ideogram",
    vendor: "Ideogram",
    origin: "US",
    kind: "image",
    lanes: ["typography"],
    price: 0.06,
    unit: "image",
    strengths: "Posters, covers, local promos — layouts where real words are part of the product.",
    watchOuts: "Not for cinematic or motion work.",
    quality: 5,
  },
  {
    id: "recraft-v3",
    name: "Recraft V3",
    family: "recraft",
    vendor: "Recraft",
    origin: "US",
    kind: "image",
    lanes: ["typography"],
    price: 0.04,
    unit: "image",
    strengths: "Design assets, vector-style campaign graphics, brand-safe layouts.",
    watchOuts: "Photoreal scenes are weaker than dedicated product models.",
    quality: 4,
  },
  {
    id: "qwen-image-edit",
    name: "Qwen Image Edit",
    family: "qwen",
    vendor: "Alibaba",
    origin: "CN",
    kind: "image",
    lanes: ["repair"],
    price: 0.03,
    unit: "image",
    strengths: "Repair shop: fix a label, replace one object, localize a headline, correct one mistake while preserving the rest.",
    watchOuts: "Not a place to develop creative direction.",
    quality: 4,
  },
  {
    id: "z-image-turbo",
    name: "Z-Image Turbo",
    family: "z-image",
    vendor: "Alibaba",
    origin: "CN",
    kind: "image",
    lanes: ["explore-image"],
    price: 0.005,
    unit: "image",
    strengths: "Very cheap still exploration — many directions quickly.",
    watchOuts: "Exploration only; don't ship tests as finals.",
    quality: 2,
  },
  {
    id: "marketing-studio-image",
    name: "Marketing Studio Image",
    family: "higgsfield-studio",
    vendor: "Higgsfield",
    origin: "US",
    kind: "image",
    lanes: ["explore-image"],
    price: 0.01,
    unit: "image",
    strengths: "Fast ad-style still concepts for hook testing.",
    watchOuts: "Exploration quality; re-render winners with a product model.",
    quality: 3,
  },
  {
    id: "pixverse-v5",
    name: "Pixverse V5",
    family: "pixverse",
    vendor: "PixVerse",
    origin: "CN",
    kind: "video",
    lanes: ["explore-video"],
    price: 0.03,
    unit: "second",
    strengths: "Cheap video tests for hooks, openings and camera ideas.",
    watchOuts: "Tests decide what's worth making — not the final deliverable.",
    quality: 2,
  },
  {
    id: "wan-2.5-fast",
    name: "Wan 2.5 Fast",
    family: "wan",
    vendor: "Alibaba",
    origin: "CN",
    kind: "video",
    lanes: ["explore-video", "speech"],
    price: 0.05,
    unit: "second",
    strengths: "Fast motion exploration; can generate speech with the scene.",
    watchOuts: "Lip sync and logos need QA.",
    quality: 3,
  },
  {
    id: "kling-2.5-turbo-std",
    name: "Kling 2.5 Turbo (Std)",
    family: "kling",
    vendor: "Kuaishou",
    origin: "CN",
    kind: "video",
    lanes: ["explore-video"],
    price: 0.06,
    unit: "second",
    strengths: "Lower-cost Kling configuration for motion tests.",
    watchOuts: "Use the pro tier for the hero shot.",
    quality: 3,
  },
  {
    id: "seedance-pro",
    name: "Seedance Pro",
    family: "seedance",
    vendor: "ByteDance",
    origin: "CN",
    kind: "video",
    lanes: ["cinematic"],
    price: 0.12,
    unit: "second",
    strengths: "Longer cinematic scenes, multiple references, sequences that develop, native audio, partial edits.",
    watchOuts: "A production model once direction is clear — not for 30 random experiments.",
    quality: 5,
  },
  {
    id: "kling-2.5-pro",
    name: "Kling 2.5 Pro",
    family: "kling",
    vendor: "Kuaishou",
    origin: "CN",
    kind: "video",
    lanes: ["hero-video"],
    price: 0.14,
    unit: "second",
    strengths: "Hero shot: camera movement, physical realism, the finish a customer notices.",
    watchOuts: "Expensive way to discover a weak idea — arrive with the shot planned.",
    quality: 5,
  },
  {
    id: "minimax-hailuo-02",
    name: "Minimax Hailuo 02",
    family: "minimax",
    vendor: "MiniMax",
    origin: "CN",
    kind: "video",
    lanes: ["speech", "explore-video"],
    price: 0.08,
    unit: "second",
    strengths: "Spokesperson and creator-style ads, localized performances.",
    watchOuts: "Lip sync and logos need a QA pass.",
    quality: 4,
  },
  {
    id: "kling-motion-control",
    name: "Kling Motion Control",
    family: "kling",
    vendor: "Kuaishou",
    origin: "CN",
    kind: "video",
    lanes: ["motion-transfer"],
    price: 0.12,
    unit: "second",
    strengths: "Apply a movement reference to a person or character — fitness, dance, demos, repeatable formats.",
    watchOuts: "Source image and motion reference must be clean; bad inputs become part of the output.",
    quality: 4,
  },
  {
    id: "topaz-upscale",
    name: "Topaz Upscale",
    family: "topaz",
    vendor: "Topaz Labs",
    origin: "US",
    kind: "image",
    lanes: ["finishing"],
    price: 0.05,
    unit: "job",
    strengths: "Resolution and detail for final delivery.",
    watchOuts: "Improves a good asset; won't rescue a bad concept.",
    quality: 5,
  },
  {
    id: "lipsync-studio",
    name: "Lipsync Studio",
    family: "lipsync",
    vendor: "Higgsfield",
    origin: "US",
    kind: "video",
    lanes: ["finishing"],
    price: 0.04,
    unit: "second",
    strengths: "Localize performances and re-time speech to new language tracks.",
    watchOuts: "Check mouth shapes on close-ups.",
    quality: 4,
  },
  {
    id: "captions-export",
    name: "Captions & Export",
    family: "export",
    vendor: "Higgsfield",
    origin: "US",
    kind: "video",
    lanes: ["finishing"],
    price: 0.01,
    unit: "job",
    strengths: "Burned-in captions, format conversion, publish-ready files.",
    watchOuts: "Verify caption copy against approved script.",
    quality: 4,
  },
  // Text models run through the Astra (OpenAI-compatible) endpoint, not
  // Higgsfield. Model IDs are configured per tier on the server:
  // COPY_FAST_MODEL, COPY_PRO_MODEL, COPY_EDIT_MODEL (all default to ASTRA_MODEL).
  {
    id: "astra-writer-fast",
    name: "Astra Writer (fast)",
    family: "astra",
    vendor: "OpenAI",
    origin: "US",
    kind: "text",
    lanes: ["copy"],
    price: 0.002,
    unit: "ktok",
    strengths: "Cheap angle and hook exploration — dozens of directions for pennies.",
    watchOuts: "Drafts, not finals: voice and claims need the pro pass.",
    quality: 3,
  },
  {
    id: "astra-writer-pro",
    name: "Astra Writer (pro)",
    family: "astra",
    vendor: "OpenAI",
    origin: "US",
    kind: "text",
    lanes: ["copy"],
    price: 0.012,
    unit: "ktok",
    strengths: "Final copy: holds voice, structure across a sequence, and the brief's constraints.",
    watchOuts: "Can drift into superlatives — QA checks claims against the approved list.",
    quality: 5,
  },
  {
    id: "astra-editor",
    name: "Astra Editor",
    family: "astra",
    vendor: "OpenAI",
    origin: "US",
    kind: "text",
    lanes: ["copy-edit"],
    price: 0.004,
    unit: "ktok",
    strengths: "Line edits: trim to length, fix a CTA, remove a spam word, repair a merge tag — keeps everything else.",
    watchOuts: "Won't fix a weak angle; regenerate for that.",
    quality: 4,
  },
];

export function getModel(id: string): ModelSpec | undefined {
  return MODEL_CATALOG.find((m) => m.id === id);
}

export function stepCost(model: ModelSpec, units: number): number {
  return model.unit === "job" ? model.price : model.price * units;
}
